<#
.SYNOPSIS
    Publish a sanitized snapshot of this PRIVATE repo to the PUBLIC distribution repo.

.DESCRIPTION
    The private repo is the source of truth (full history, internal docs, client
    references). The public repo is a downstream snapshot regenerated by this
    script -- the two are NEVER connected at the git level, so private history
    can never leak.

    Flow:
      1. Export the tracked files at HEAD (binary-safe zip -> no history).
      2. Strip internal-only paths that must never be public.
      3. Leak-check the staged tree; abort hard if any client/internal term slips through.
      4. Mirror the clean tree into a separate clone of the public repo and push.

    This script itself is PRIVATE-only (its detection pattern lists the very
    terms it guards against) and is excluded from the public snapshot.

.PARAMETER PublicDir
    Path to a local clone of the PUBLIC repo (its own .git is preserved).

.PARAMETER Version
    Optional version label for the release commit (e.g. v0.7.1).

.EXAMPLE
    ./publish.ps1 -PublicDir C:\dev\sidekick-copilot-public -Version v0.7.1
#>
param(
    [Parameter(Mandatory)][string]$PublicDir,
    [string]$Version = ""
)
$ErrorActionPreference = "Stop"

# --- Paths/files that must NEVER be published (relative to repo root) ---
$ExcludePaths = @(
    "sidekick/docs",   # internal design/test notes (verbatim client meeting excerpts)
    "publish.ps1"      # this script (contains the client-term detection pattern)
)

# --- Client / internal / person terms that must not appear in the public tree ---
$LeakPattern = "HMRC|Ministry of Justice|\bMoJ\b|\bmoj\b|HMCTS|\bhmcts\b|\bSRA\b|" +
    "Solicitors Regulation|His Majesty|Denodo|\bCDIO\b|Caseworker|Crime MI|\bCCG\b|" +
    "eng\.ms|EngineeringHub|EngHub|Cabinet Office|Dayforce|Esdale|Trystan|Bharti|" +
    "\bKola\b|\bKenni\b"

if (-not (Test-Path (Join-Path $PublicDir ".git"))) {
    throw "PublicDir '$PublicDir' is not a git clone. Clone the public repo there first."
}

# 1. Export tracked files at HEAD (zip is binary-safe; git archive carries no history).
$stage = Join-Path $env:TEMP ("sk-publish-" + [guid]::NewGuid().ToString("N"))
New-Item -ItemType Directory -Path $stage | Out-Null
$zip = "$stage.zip"
git archive --format=zip -o $zip HEAD
Expand-Archive -Path $zip -DestinationPath $stage -Force
Remove-Item $zip -Force

# 2. Strip internal-only paths.
foreach ($p in $ExcludePaths) {
    $full = Join-Path $stage $p
    if (Test-Path $full) { Remove-Item $full -Recurse -Force }
}

# 3. Leak check -- fail hard before anything reaches the public clone.
$files = Get-ChildItem $stage -Recurse -File | Where-Object { $_.Extension -ne ".vsix" }
$hits = Select-String -Path $files.FullName -Pattern $LeakPattern -ErrorAction SilentlyContinue
if ($hits) {
    Write-Host "LEAK CHECK FAILED -- publish aborted. Offending lines:" -ForegroundColor Red
    $hits | ForEach-Object {
        Write-Host ("  " + $_.Path.Replace($stage, "") + ":" + $_.LineNumber + "  " + $_.Line.Trim())
    }
    Remove-Item $stage -Recurse -Force
    exit 1
}
Write-Host "Leak check clean." -ForegroundColor Green

# 4. Mirror into the public clone (preserve its .git) and push.
robocopy $stage $PublicDir /MIR /XD ".git" /NFL /NDL /NJH /NJS /NC /NS | Out-Null
Push-Location $PublicDir
git add -A
if ((git status --porcelain).Length -eq 0) {
    Write-Host "No changes to publish." -ForegroundColor Yellow
} else {
    $msg = if ($Version) { "Release $Version" } else { "Sync $(Get-Date -Format yyyy-MM-dd)" }
    git commit -m $msg
    git push origin main
    Write-Host "Published '$msg' to $PublicDir" -ForegroundColor Green
}
Pop-Location
Remove-Item $stage -Recurse -Force
